# Generated by Django 2.0.1 on 2018-05-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomBlockCompletelyDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=256)),
                ('drug_name', models.CharField(max_length=256)),
                ('block', models.IntegerField()),
                ('druf', models.IntegerField()),
                ('build_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
