# Generated by Django 2.0.1 on 2018-05-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomblockcompletelydesign',
            name='druf',
        ),
        migrations.AddField(
            model_name='randomblockcompletelydesign',
            name='build_user',
            field=models.CharField(default='admin', max_length=128),
        ),
        migrations.AddField(
            model_name='randomblockcompletelydesign',
            name='drug',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='randomblockcompletelydesign',
            name='block',
            field=models.IntegerField(default=0),
        ),
    ]
