# Generated by Django 2.0.1 on 2018-06-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0002_auto_20180531_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomblockcompletelydesign',
            name='class_name',
            field=models.CharField(default='design', max_length=16),
        ),
    ]
