# Generated by Django 2.0.1 on 2018-06-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0003_randomblockcompletelydesign_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomblockcompletelydesign',
            name='title',
            field=models.CharField(default='随机区组试验', max_length=256),
        ),
    ]
